interface AdminNotificationEmailProps {
  referenceNumber: string
  submissionDate: string
  name: string
  email: string
  rights: string[]
  description: string
  method: string
  feedbackMethod: string
}

export function AdminNotificationEmail({
  referenceNumber,
  submissionDate,
  name,
  email,
  rights,
  description,
  method,
  feedbackMethod,
}: AdminNotificationEmailProps) {
  return (
    <div style={{ fontFamily: "Arial, sans-serif", maxWidth: "700px", margin: "0 auto", padding: "20px" }}>
      <div
        style={{
          backgroundColor: "#dc3545",
          color: "white",
          padding: "20px",
          borderRadius: "8px",
          marginBottom: "20px",
        }}
      >
        <h1 style={{ margin: "0", textAlign: "center" }}>🚨 New Rights Request</h1>
        <p style={{ textAlign: "center", fontSize: "18px", fontWeight: "bold", margin: "10px 0 0 0" }}>
          Reference: {referenceNumber}
        </p>
      </div>

      <div style={{ backgroundColor: "#f8f9fa", padding: "15px", borderRadius: "5px", marginBottom: "20px" }}>
        <h3 style={{ color: "#495057", marginTop: "0" }}>Submission Overview</h3>
        <p>
          <strong>Submitted by:</strong> {name}
        </p>
        <p>
          <strong>Email:</strong> {email || "Not provided"}
        </p>
        <p>
          <strong>Date:</strong> {submissionDate}
        </p>
        <p>
          <strong>Method:</strong> {method}
        </p>
        <p>
          <strong>Preferred Response:</strong> {feedbackMethod}
        </p>
      </div>

      <div style={{ marginBottom: "20px" }}>
        <h3 style={{ color: "#495057" }}>Rights Requested:</h3>
        <ul style={{ backgroundColor: "#fff3cd", padding: "15px", borderRadius: "5px" }}>
          {rights.map((right, index) => (
            <li key={index} style={{ marginBottom: "5px" }}>
              {right}
            </li>
          ))}
        </ul>
      </div>

      <div style={{ marginBottom: "20px" }}>
        <h3 style={{ color: "#495057" }}>Request Description:</h3>
        <div style={{ backgroundColor: "#e9ecef", padding: "15px", borderRadius: "5px", whiteSpace: "pre-wrap" }}>
          {description}
        </div>
      </div>

      <div style={{ backgroundColor: "#d1ecf1", padding: "15px", borderRadius: "5px", marginBottom: "20px" }}>
        <h3 style={{ color: "#0c5460", marginTop: "0" }}>⏰ Action Required</h3>
        <p style={{ color: "#0c5460", margin: "0" }}>
          This request must be processed within 30 days as required by law. Please review and respond according to your
          data protection procedures.
        </p>
      </div>

      <div style={{ borderTop: "1px solid #dee2e6", paddingTop: "15px", fontSize: "12px", color: "#6c757d" }}>
        <p>This notification was automatically generated by the Rights Request System.</p>
      </div>
    </div>
  )
}
